### ISSUE TITLE
bug: emitters not working

### ISSUE THREAD

**Issue by devnote-dev** [PteroPackages/PteroJS#14]
For some strange reason, the emit functions in `RestRequestManager` throw an internal Node error, they've been commented out currently for functionality.
```
TypeError: domain.enter is not a function
    at RestRequestManager.emit (node:domain:536:10)
    at RestRequestManager.debug (C:\...\PteroJS\src\http\RestRequestManager.ts:41:15)
    at RestRequestManager._make (C:\...\PteroJS\src\http\RestRequestManager.ts:65:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
https://github.com/PteroPackages/PteroJS/blob/ea99ba32cae6eaef099598fd72e8014566a7cf72/src/http/RestRequestManager.ts#L41

**Comment by devnote-dev** [comment]
Fixed in [5f36b2a9](https://github.com/PteroPackages/PteroJS/commit/5f36b2a9dd0df92e7beb00b5b503808034b2fa37), needs to be reflected in rewrite branch.
