### ISSUE TITLE
Fetching server causes a "maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by kivox** [PteroPackages/PteroJS#25]
```
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:300:21)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)
    at toSnakeCase (file:///home/petar/go/src/github.com/kivox/panel/node_modules/@devnote-dev/pterojs/dist/index.mjs:323:11)

**Comment by devnote-dev** [comment]
How many servers do you have on your panel? Keep in mind that `#fetchAll` is recursive and will attempt to cycle through every page of servers available.

**Comment by kivox** [comment]
> How many servers do you have on your panel? Keep in mind that `#fetchAll` is recursive and will attempt to cycle through every page of servers available.

I've only got about 20 servers on the panel, so it shouldn't really be an issue. I have a feeling webpack or some of the underlying NextJS code might be at fault, as normal js works perfectly fine.

**Comment by WavingCatDevs** [comment]
I am also getting this issue also with Express. I haven't got many servers.

**Comment by kivox** [comment]
Some additional info

Attempted to fix it, but it's not the correct fix, the issue steps from the toJSON conversion.

```
import { type NextApiRequest, type NextApiResponse } from "next";
import { pteroAdmin } from "~/server/pterodactyl";

const handler = async (req: NextApiRequest, res: NextApiResponse) => {
  const server = await pteroAdmin.servers.fetch("test");

  return res.status(200).json(server);
};

export default handler;
```

Same error occurs with `res.status(200).json(server.toJSON());`, but when I use `server.id` instead of just `server` it works fine.

**Comment by kivox** [comment]
.toJSON() is also affected. `console.log(server)` works but `console.log(server.toJSON());` doesn't

**Comment by kivox** [comment]
```
const pteroSrv = await ctx.pteroAdmin.servers.fetch(srv.id);

return {
   ...server
}
```

Causes the following error
```
Converting circular structure to JSON
    --> starting at object with constructor 'PteroApp'
    |     property 'allocations' -> object with constructor 'NodeAllocationManager'
    --- property 'client' closes the circle
```

Using the library built-in toJSON causes `Maximum call stack size exceeded`

**Comment by devnote-dev** [comment]
It looks like there's still objects in the `ApplicationServer` class that the case conversion functions are trying to handle which are evidently circularly-referenced, hence the recursion issues. I'll need to do more debugging into it to see what fields cause it though.

**Comment by FC5570** [comment]
I've had this same issue. Try deleting the database property from the ApplicationServer object and then calling .toJSON()
